/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const add: (a: number, b: number) => number;
export const build_grid_with_heightmap: (a: any, b: number) => any;
export const edit_heightmap: (a: any, b: any) => any;
export const edit_heightmap_h: (a: any) => any;
export const generate_biomes: (a: any, b: any, c: any) => any;
export const generate_biomes_for_grid: (a: any) => any;
export const generate_climate: (a: any, b: any, c: any) => any;
export const generate_climate_for_grid: (a: any, b: any) => any;
export const generate_cultures_religions: (a: any, b: number, c: number, d: number, e: any) => any;
export const generate_heightmap: (a: any, b: number) => any;
export const generate_mesh: (a: number, b: number) => any;
export const generate_states: (a: any, b: number, c: number) => any;
export const generate_timeline: (a: any, b: any, c: any, d: any, e: any, f: any, g: any, h: bigint, i: any) => any;
export const generate_world: (a: number, b: number, c: any) => any;
export const get_drainage_geometry_h: () => any;
export const has_grid_h: () => number;
export const init: () => void;
export const pick_cell: (a: any, b: number, c: number) => number;
export const pick_cell_h: (a: number, b: number) => number;
export const project_delta: (a: any, b: any, c: number, d: number) => any;
export const project_world: (a: any, b: any, c: any, d: any, e: any, f: any, g: number) => any;
export const recompute_dependents: (a: any, b: any) => any;
export const recompute_dependents_h: (a: any) => any;
export const recompute_dependents_h2: (a: any) => any;
export const recompute_temp_biome_local: (a: any, b: any, c: any) => any;
export const recompute_temp_biome_local_h: (a: any, b: any) => any;
export const release_grid_h: () => void;
export const reset_heightmap: (a: any) => any;
export const reset_heightmap_h: () => any;
export const store_grid_h: (a: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
